### ISSUE TITLE
TypeError: Callback is not a function

### ISSUE THREAD

**Issue by Ironboltx** [nzapponi/homebridge-simplisafe3#123]
Hi. Sorry for all the issues. So I started simplisafe and then I got this error

TypeError: callback is not a function
    at SS3SimpliCam.identify (/usr/local/lib/node_modules/homebridge-simplisafe3/accessories/simplicam.js:98:5)
    at PlatformAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-simplisafe3/accessories/simplicam.js:103:52)
    at PlatformAccessory.emit (events.js:315:20)
    at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:85:12)
    at Accessory.emit (events.js:315:20)
    at Accessory.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Accessory._this._identificationRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:256:12)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1599:16)
    at Characteristic.emit (events.js:315:20)
    at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)

Do I need to turn off my firewall or rebuild node? Please help. Thanks!!

**Comment by nikonratm** [comment]
What version of homebridge are you using? If it was working before I would guess you changed something...

**Comment by nikonratm** [comment]
You did not use the issue template, please update this issue with the correct information.

**Comment by nikonratm** [comment]
The error makes me think you changed your version of homebridge or something, especially since it was working fine for you before.

Closing because you did not use the issue template, please update this issue with the correct information if needed.

**Comment by nikonratm** [comment]
@Ironboltx my sincerest apologies, you are correct there is a bug, it only happens when you are setting up the system (a big deal, obv) or if you hit "ID" in the Eve app, for example. I will release a fix soon. Thanks for your understanding.
