### ISSUE TITLE
SSAPI token refresh failed

### ISSUE THREAD

**Issue by thrangster** [nzapponi/homebridge-simplisafe3#139]
**Describe The Bug:**
 Plug in stops function after several minutes. Home app reports no response from any Simplisafe device, and no camera feeds. Restart of Homebridge fixes the issue but only for several minutes, then it recurs.

**To Reproduce:**
just let it run..

**Expected behavior:**
 Connectivity should not timeout...

[**Logs:**]()

For when Home completely loses SimpliSafe functionality (no response for any devices/cameras), I see:

[7/15/2020, 10:43:35] [Home Alarm] SSAPI token refresh failed, request blocked (rate limit?)

```
Paste Homebridge Logs here
```

**Homebridge Config:**

"bridge": {
        "name": "Homebridge xxxx",
        "username": "xxxx",
        "port": 51083,
        "pin": "xxxxxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "debug": true,
            "platform": "config"
        },

```json
Paste the relevant section of your homebridge config.json here
```
{
            "name": "Home Alarm",
            "auth": {
                "username": "xxxxx",
                "password": "xxxxx"
            },
            "cameras": true,
            "debug": true,
            "sensorRefresh": 15,
            "persistAccessories": false,
            "resetSimpliSafeId": false,
            "cameraOptions": {
                "enableHwaccelRpi": true
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"

**Screenshots:**

**Environment:**

* **Plugin version**:  1.6.7
* **Node.js Version**:  12.18.1
* **NPM Version**:  6.14.5
* **Homebridge Version**:  0.5.0 RC20
* **Operating System**:  Raspbian

**Comment by shamoon** [comment]
Hi @thrangster , how long have you been having this issue? You may be getting rare limited by SS which usually resolves after a matter of hours or a day, but the plugin should do its best to mitigate this by pinging SS less frequently. Can you please make sure you have the debug `-D` option enabled for homebridge and post a longer section of your logs (should have more info with that enabled)

**Comment by thrangster** [comment]
Well, I rebooted as suggested, and the SSAPI token refresh failed, request blocked (rate limit?) error returned.

Does this happened every time one reboots the Homebridge? Or is there something else I need to look at? 

Thanks

**Comment by thrangster** [comment]
Did another reboot and good for two hours, then it recurs...

[7/15/2020, 15:57:37] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":359,"sid":"uuid:148","control":"_0","action":120,"node":"","eventInfo":""}
[7/15/2020, 15:58:02] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":360,"sid":"uuid:148","control":"_0","action":120,"node":"","eventInfo":""}
[7/15/2020, 15:58:26] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":361,"sid":"uuid:148","control":"_0","action":120,"node":"","eventInfo":""}
[7/15/2020, 15:58:47] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":362,"sid":"uuid:148","control":"_0","action":120,"node":"","eventInfo":""}
[7/15/2020, 15:59:12] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":363,"sid":"uuid:148","control":"_0","action":120,"node":"","eventInfo":""}
[7/15/2020, 15:59:36] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":364,"sid":"uuid:148","control":"_0","action":120,"node":"","eventInfo":""}
[7/15/2020, 15:59:56] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":365,"sid":"uuid:148","control":"_0","action":120,"node":"","eventInfo":""}
[7/15/2020, 16:00:22] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":366,"sid":"uuid:148","control":"_0","action":120,"node":"","eventInfo":""}
[7/15/2020, 16:00:47] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":367,"sid":"uuid:148","control":"_0","action":120,"node":"","eventInfo":""}
[7/15/2020, 16:01:07] [isy-nodejs] ZWave Front Porch - Glass Break Ala (ZW003_118): Command Luminance (LUMIN) triggered.
[7/15/2020, 16:01:08] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":372,"sid":"uuid:148","control":"_0","action":120,"node":"","eventInfo":""}
**

> [7/15/2020, 16:01:21] [Home Alarm] SSAPI token refresh failed, request blocked (rate limit?).

**
[7/15/2020, 16:01:33] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":373,"sid":"uuid:148","control":"_0","action":120,"node":"","eventInfo":""}
[7/15/2020, 16:01:57] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":374,"sid":"uuid:148","control":"_0","action":120,"node":"","eventInfo":""}
[7/15/2020, 16:02:18] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":375,"sid":"uuid:148","control":"_0","action":120,"node":"","eventInfo":""}
[7/15/2020, 16:02:39] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":376,"sid":"uuid:148","control":"_0","action":120,"node":"","eventInfo":""}
[7/15/2020, 16:03:04] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":377,"sid":"uuid:148","control":"_0","action":120,"node":"","eventInfo":""}
[7/15/2020, 16:03:27] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":378,"sid":"uuid:148","control":"_0","action":120,"node":"","eventInfo":""}
[7/15/2020, 16:03:34] [Ring] No snapshot cached for Front Door
[7/15/2020, 16:03:34] [Ring] Loading new snapshot into cache for Front Door
[7/15/2020, 16:03:35] [Ring] Snapshot cached for Front Door (0.788s)
[7/15/2020, 16:03:44] [Ring] Used cached snapshot for Front Door


Odd....

**Comment by thrangster** [comment]
When I touched a SS camera during this No Response state, I saw this in the log if helpful

[7/15/2020, 16:06:26] [Home Alarm] Prepare stream with request: {
  sessionID: 'c0d3a248-9818-469f-a2d8-febc21680bb',
  targetAddress: '192.168.0.178',
  addressVersion: 'ipv4',
  video: {
    port: 53335,
    srtpCryptoSuite: 0,
    srtp_key: <Buffer 20 9f 84 e4 d3 23 fb 5a ec fc 33 9f 57 b1 8e 3a>,
    srtp_salt: <Buffer da fa 68 8c 02 9b 60 26 a7 15 0e 2b d1 37>
  },
  audio: {
    port: 51236,
    srtpCryptoSuite: 0,
    srtp_key: <Buffer 69 fe d3 32 0a 77 78 7d d9 48 08 2a 8b 33 e8 01>,
    srtp_salt: <Buffer 16 7b 6b 95 be 1c fd b5 f0 b4 d4 b6 dd 77>
  }
}
[7/15/2020, 16:06:26] [Home Alarm] handleStreamRequest with request: {
  sessionID: 'c0d3a248-9818-469f-a2d8-febc21680bb',
  type: 'start',
  video: {
    profile: 2,
    level: 2,
    packetizationMode: 0,
    cvoId: undefined,
    width: 1280,
    height: 720,
    fps: 30,
    pt: 99,
    ssrc: 3256465807,
    max_bit_rate: 299,
    rtcp_interval: 0.5,
    mtu: 1378
  },
  audio: {
    codec: 'AAC-eld',
    channel: 1,
    bit_rate: 0,
    sample_rate: 16,
    packet_time: 30,
    pt: 110,
    ssrc: 838977725,
    max_bit_rate: 24,
    rtcp_interval: 5,
    comfort_pt: 13,
    comfortNoiseEnabled: false
  }
}
[7/15/2020, 16:06:26] [Home Alarm] Error: Camera stream request blocked (rate limited)
    at SS3SimpliCam.handleStreamRequest (/usr/local/lib/node_modules/homebridge-simplisafe3/accessories/simplicam.js:341:21)
    at RTPStreamManagement._handleStartStream (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:791:19)
    at RTPStreamManagement._handleSelectedStreamConfigurationWrite (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:622:14)
    at Characteristic.emit (events.js:315:20)
    at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:651:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1437:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1279:10)
    at HAPServer.emit (events.js:315:20)

**Comment by shamoon** [comment]
Since the issue is not widespread I am confident its just because you've been messing around with the plugin and are intermittently getting blocked. One thing you can do when it happens is check if you can login to the SS website control panel (if youre blocked you shouldn't be able to). I suggest we it some time undisturbed (perhaps even with HB / the plugin disabled) and see how things shake out.

**Comment by shamoon** [comment]
(I dont mean messing around in a pejorative way, just that you've been playing with getting it setup etc)

**Comment by thrangster** [comment]
Lol - well, not too much messing around with the SS plug in at all, in fact when it stops working I'm not even logged into the Homebridge.

I have been adding lights to my ISY plug in, so there have been several HB restarts - not sure if global restarts impact this.

But good check - when it happens I will try and log into the site (I can tell you the app continues to work during this condition if that matters)

Thanks - and no pejorative taken...!

**Comment by shamoon** [comment]
Yea restarting HB will re-login to SS so might play a role, its not just how many total logins its also how close together. For example if you set the sensor refresh time to something very short like 5s it can get you blocked (at least that was true last time I tried that). 

If this happens again after a real period of things working and no playing around =) then please post logs with the `-D` option enabled and I'll take another look!

**Comment by thrangster** [comment]
Thanks - yes I was adding small groups go lighting which required a restart each time, at least yesterday, so I'll keep and eye on it.

Thanks for your prompt and thorough help
