### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Request failed with status code 401

### ISSUE THREAD

**Issue by tjenvy** [nzapponi/homebridge-simplisafe3#145]
Getting a repeating error on the console for a rejection.  It repeats every 1/2 second.  within 10 hours its made 33440 messages.  

unknown what is causing the error.  Standard usage, launch, operate as normal.

(node:44370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 33490)
(node:44370) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
    at createError (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by shamoon** [comment]
Hi @tjenvy error 401 means unauthorized. When this happens are you able to login to your account on the web? And have you double-checked your login credentials? No reason to let this run for 10 hours (though agreed we should add something to prevent this) as it will never succeed.

**Comment by tjenvy** [comment]
Yes everything functions without issue. Just the repeating error.  I can co trip the system and I can also run the app and the website without error.

**Comment by shamoon** [comment]
The issue template includes an area to paste your config, please send it (with details X out). Have you double-checked your login details in homebridge? And not just running the app, ensure you can login to the site from scratch. I dont see another explanation (and this issue is limited to your install it seems).

**Comment by badmaj5** [comment]
Was there any resolution to this? I just set up my HomeBridge today and after working for a little while, I noticed this same error. I restarted the raspberry pi and now I’m getting an error that it can’t login to SimpliSafe. I checked the website and my account has been locked due to too many failed login attempts. Is there something specific I need to change in the config file to prevent the plugin from trying & failing to log in repeatedly?

**Comment by shamoon** [comment]
Hmm, if you have logs that might be helpful but the error is odd if your login details were correct (are you certain they were?). Also this app only “logs in” at startup and after that refreshes a token and when you restarted it presumably saw you were locked out and gave up. If you unlock your account does that solve it? Also hard to tell from your description if you’re getting “rate-limited” which is an annoying thing SimpliSafe do that some people here experience. The plugin tries to handle that situation but there may be an issue it’s missing.

**Comment by badmaj5** [comment]
I had to wait an hour for SimpliSafe to unlock my account and then I changed the password. It is working again now. If it happens again I’ll try to figure out how to copy out the log of the error I’m getting.

**Comment by badmaj5** [comment]
It was working again for a while, and I’ve got the same error again. It is repeating the same error every second or seems.  Looks to me like it is error in on the token refresh you described. Here is the relevant config information along with the error on the log.


![19CC3001-86F5-49E3-8DAF-9C0581EABBF8](https://user-images.githubusercontent.com/62351369/95692761-c7130800-0bed-11eb-8f3e-ff89ca7e7686.jpeg)



![D086BF48-5A79-4594-921B-9BEC0E93F373](https://user-images.githubusercontent.com/62351369/95692712-5f5cbd00-0bed-11eb-88ca-1a76f42ae731.jpeg)

**Comment by shamoon** [comment]
@badmaj5 do you by any chance have the logs _before_ that part you sent a screenshot of? Ideally from startup all the way through the error. If you can upload the file or copy/paste that would be great. I have some ideas for how to track this down but that would be helpful.

**Comment by badmaj5** [comment]
Here is what I think is the relevant dump of the log from the time I re-installed the SimpliSafe plugin all the way until it errors. At one point it tells me to check my email to verify my account, which I did. You can see there is about 10 minutes where things seem to be working until the error starts happening. The log is tens of thousands of lines of the same error being repeated.

By the way, it is amazing there are people like you who put things like this together and then are willing to respond and try to help people figure things out! 

![C823149D-707C-4601-8FC9-9F993AC29D83](https://user-images.githubusercontent.com/62351369/95696541-24fd1b00-0c01-11eb-9c65-b42bf5bb8c9d.jpeg)
![8E0B0D99-DF41-438D-8834-426CF3635DF4](https://user-images.githubusercontent.com/62351369/95696544-262e4800-0c01-11eb-9754-0ddb48b0eacd.png)

**Comment by shamoon** [comment]
@badmaj5 Challenging but _I think_ I've got this sorted. Turns out this would happen when the plugin was first setup where it would check for SimpliSafe's multi factor authentication (email) but would keep checking even after it was approved. This would persist and after 10 minutes get you blocked. I'm guessing once you were blocked you were on a shortlist where even normal plugin function was enough to get you blocked again.

So obviously you can/should update to v1.6.10 but since youre already blocked you may need to leave the plugin turned off for a day or so (or hours, we dont really know) to get yourself un-blocked. After that Im hopeful you'll be good.

Let us know how you get on! And thanks for the kind words, fun to have a hobby others can enjoy 👍🏼

**Comment by badmaj5** [comment]
Thanks for looking into this! It seems to be working for me now!
