### ISSUE TITLE
TypeError: plugin.initializer is not a function

### ISSUE THREAD

**Issue by JimDog546** [nzapponi/homebridge-simplisafe3#2]
Added homebridge-simplisafe3 to a successfully working Homebridge installation on macOS.  Receiving the following error when trying to start Homebridge after adding necessary config to config.json:

[2019-6-23 16:07:25] Loaded plugin: homebridge-simplisafe3
/usr/local/lib/node_modules/homebridge/lib/server.js:160
      plugin.initializer(this._api);
             ^

TypeError: plugin.initializer is not a function
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:160:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:138:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by JimDog546** [comment]
I updated homebridge to the latest version and also found I had a missing comma in my config.json.  No longer experiencing the error message.
