### ISSUE TITLE
unable to start plugin

### ISSUE THREAD

**Issue by shaunakkulkarni** [nzapponi/homebridge-simplisafe3#49]
Hello, 

I am getting the following error when trying to start this plugin: 
TypeError: Cannot read property 'name' of null
    at new SS3Platform (/usr/lib/node_modules/homebridge-simplisafe3/index.js:45:24)
    at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:358:30)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:92:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)

Here is my config file:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CB:22:3D:E2:CE:31",
        "port": 51826,
        "pin": "033-44-254"
    },
    "accessories": [],
    "platforms": [
{
        "platform" : "homebridge-simplisafe3.SimpliSafe 3",
        "name" : "Home Alarm",
        "auth":{
                "username" : "myusername@yahoo.com",
                "password" : "mypassword1#"
},
"cameras": true
}

]
}  

any help would be appreciated! Thanks for the awesome plugin!

**Comment by nikonratm** [comment]
That type of error is usually not really an issue with this plugin itself, it means its not even loading your config file. What node version are you using? Also, are you able to start Homebridge successfully without any plugins? Double-check the location of the config, etc.

**Comment by shaunakkulkarni** [comment]
the node version is 12.13.1, the config file is located at: /var/lib/homebridge/config.json. runs fine without any plugins. Sorry if there's an obvious answer but this is my first home bridge installation so I'm a little new to everything

**Comment by shaunakkulkarni** [comment]
Nevermind I got it- turns out my config file was in the wrong directory.
