### ISSUE TITLE
Cannot read property 'name' of null

### ISSUE THREAD

**Issue by valdan87** [nzapponi/homebridge-simplisafe3#5]
Just installed this plugin on a new Node.js install and can't get it it initialize. I've put in username and password, but keep getting the following error when I launch Homebridge. Any help would be awesome, as I love using SimpliSafe 3!

`Load homebridge-simplisafe3.SimpliSafe 3
[7/7/2019, 10:34:37 PM] TypeError: Cannot read property 'name' of null
    at new SS3Platform (/usr/local/lib/node_modules/homebridge-simplisafe3/index.js:27:24)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:358:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:92:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)`

**Comment by nzapponi** [comment]
@valdan87 what version of Node are you running?

**Comment by nzapponi** [comment]
Potentially similar to #4

**Comment by valdan87** [comment]
Thanks for the reply! I'm on v12.5.0 as of right now. Thank you!

**Comment by nzapponi** [comment]
@valdan87 can you please provide your config.json file, replacing your username and password with some fake data?

**Comment by nzapponi** [comment]
Closing as it's been a while. Please re-open if the issue arises again.
