### ISSUE TITLE
Error Loading Plugin: undefined

### ISSUE THREAD

**Issue by spdee** [nzapponi/homebridge-simplisafe3#6]
Hello @nzapponi! Great plugin, I believe you have the most feature-packed platform for SimpliSafe Homebridge integration so kudos! Unfortunately I cannot load the platform and I'm guessing it might just be too new of a Homebridge install on a Pi or some dependency issue?

I'm running Node v12.7.0 and Homebridge v0.4.50 and latest (1.1.1) of your plugin.

Here is the error I'm getting: 
```[7/27/2019, 10:48:20 AM] Loaded config.json with 0 accessories and 1 platforms.
[7/27/2019, 10:48:20 AM] ---
[7/27/2019, 10:48:21 AM] ====================
[7/27/2019, 10:48:21 AM] ERROR LOADING PLUGIN homebridge-simplisafe3:
[7/27/2019, 10:48:21 AM] undefined
[7/27/2019, 10:48:21 AM] ====================
[7/27/2019, 10:48:21 AM] No plugins found. See the README for information on installing plugins.
[7/27/2019, 10:48:21 AM] Loading 1 platforms...
[7/27/2019, 10:48:21 AM] Error: The requested platform 'homebridge-simplisafe3.SimpliSafe 3' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:140:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
[7/27/2019, 10:48:21 AM] Got SIGTERM, shutting down Homebridge...
```

And here is my config.json:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "homebridge-simplisafe3.SimpliSafe 3",
            "name": "Home Alarm",
            "auth": {
                "username": "username",
                "password": "password"
            },
            "cameras": false
        }
    ]
}
```

**Comment by spdee** [comment]
Would be good info to add that I have also tried all previous versions of your plugin back to 1.0.4 and same effect each time. Homebridge isnt that newly updated AFAIK (a couple months at least) and not sure if Node version (12.7.0) could be the issue?

**Comment by nzapponi** [comment]
Hi @spdee, it seems like there plugin hasn't loaded. Check that you have installed the npm package correctly and that you have restarted Homebridge after installation! Thanks

**Comment by spdee** [comment]
@nzapponi this is the output of the npm install:

```pi@raspberrypi:/var/lib/homebridge $ sudo npm install -g homebridge-simplisafe3

> @ffmpeg-installer/linux-arm@4.1.3 postinstall /usr/lib/node_modules/homebridge-simplisafe3/node_modules/@ffmpeg-installer/linux-arm
> chmod u+x ffmpeg

chmod: changing permissions of 'ffmpeg': Operation not permitted

> @ffmpeg-installer/linux-arm64@4.1.3 postinstall /usr/lib/node_modules/homebridge-simplisafe3/node_modules/@ffmpeg-installer/linux-arm64
> chmod u+x ffmpeg

chmod: changing permissions of 'ffmpeg': Operation not permitted
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/darwin-x64@4.1.0 (node_modules/homebridge-simplisafe3/node_modules/@ffmpeg-installer/darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/darwin-x64@4.1.0: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-ia32@4.1.0 (node_modules/homebridge-simplisafe3/node_modules/@ffmpeg-installer/linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-ia32@4.1.0: wanted {"os":"linux","arch":"ia32"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-x64@4.1.0 (node_modules/homebridge-simplisafe3/node_modules/@ffmpeg-installer/linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-x64@4.1.0: wanted {"os":"linux","arch":"x64"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/win32-ia32@4.1.0 (node_modules/homebridge-simplisafe3/node_modules/@ffmpeg-installer/win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/win32-ia32@4.1.0: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/win32-x64@4.1.0 (node_modules/homebridge-simplisafe3/node_modules/@ffmpeg-installer/win32-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/win32-x64@4.1.0: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm@4.1.3 (node_modules/homebridge-simplisafe3/node_modules/@ffmpeg-installer/linux-arm):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm@4.1.3 postinstall: `chmod u+x ffmpeg`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm64@4.1.3 (node_modules/homebridge-simplisafe3/node_modules/@ffmpeg-installer/linux-arm64):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm64@4.1.3 postinstall: `chmod u+x ffmpeg`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ homebridge-simplisafe3@1.1.1
added 34 packages from 30 contributors in 90.154s
```

**Comment by spdee** [comment]
Hmm, even totally removed Node and reinstalled v10.16 and homebridge + this plugin and same result: `ERROR LOADING PLUGIN undefined`

**Comment by nzapponi** [comment]
Could you please share your config.json? (Make sure you mask username and password)!

**Comment by spdee** [comment]
@nzapponi it's in the first post, thanks for checking into it for me! :)

**Comment by nzapponi** [comment]
@spdee that's really strange, no error, just undefined... Can you confirm that you can successfully login to https://webapp.simplisafe.com/ using the username and password you entered in `config.json`, and that you can successfully enable/disable the alarm?

Ideally, please test this from the same network that your Homebridge device is connected to.

**Comment by nzapponi** [comment]
@spdee can you please try to re-install the plugin using the `--unsafe-perm` flag?

`npm install -g --unsafe-perm homebridge-simplisafe3`

Let me know, thanks.

**Comment by nikonratm** [comment]
I had the same issue and the `--unsafe-perm` flag fixes it, think you should close this issue.
