### ISSUE TITLE
Error: The requested platform 'homebridge-simplisafe3.SimpliSafe 3' was not registered by any plugin.

### ISSUE THREAD

**Issue by alexcf** [nzapponi/homebridge-simplisafe3#99]
Hi there,

I eagerly upgraded this morning 😉  - although now stuck in a loop. Any ideas?

[28/04/2020, 10:27:46] Loading 3 platforms...
[28/04/2020, 10:27:46] [Config] Initializing config platform...
[28/04/2020, 10:27:46] [Config] Running in Service Mode
[28/04/2020, 10:27:46] Error: The requested platform 'homebridge-simplisafe3.SimpliSafe 3' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:140:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
[28/04/2020, 10:27:46] Got SIGTERM, shutting down Homebridge...
[28/04/2020, 10:27:51] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[28/04/2020, 10:27:56] [HB Supervisor] Restarting Homebridge...
[28/04/2020, 10:27:56] [HB Supervisor] Starting Homebridge with extra flags: -I
[28/04/2020, 10:27:56] [HB Supervisor] Started Homebridge with PID: 1574
[28/04/2020, 10:27:57] Loaded config.json with 0 accessories and 3 platforms.
[28/04/2020, 10:27:57] ---
[28/04/2020, 10:27:57] Loaded plugin: homebridge-config-ui-x
[28/04/2020, 10:27:57] Registering platform 'homebridge-config-ui-x.config'
[28/04/2020, 10:27:57] ---
[28/04/2020, 10:27:57] Loaded plugin: homebridge-ring
[28/04/2020, 10:27:57] Registering platform 'homebridge-ring.Ring'
[28/04/2020, 10:27:57] ---
[28/04/2020, 10:27:57] ====================
[28/04/2020, 10:27:57] ERROR LOADING PLUGIN homebridge-simplisafe3:
[28/04/2020, 10:27:57] Error: Cannot find module '/usr/lib/node_modules/homebridge-simplisafe3/index.js'
Require stack:
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:73:23)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:153:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/usr/lib/node_modules/homebridge/lib/server.js:145:22)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:57:24)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:32:16)
[28/04/2020, 10:27:57] ====================
[28/04/2020, 10:27:57] Loading 3 platforms...
[28/04/2020, 10:27:57] [Config] Initializing config platform...
[28/04/2020, 10:27:57] [Config] Running in Service Mode
[28/04/2020, 10:27:57] Error: The requested platform 'homebridge-simplisafe3.SimpliSafe 3' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:140:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
[28/04/2020, 10:27:57] Got SIGTERM, shutting down Homebridge...

**Comment by nikonratm** [comment]
Hmm, @alexcf there weren't any major changes that would explain this. You mean you upgraded homebridge or just this plugin? Can you try re-installing the plugin please?

**Comment by alexcf** [comment]
I found this randomly - https://github.com/nzapponi/homebridge-simplisafe3/issues/6. I removed the plugin and used unsafe-perms which seems to have fixed it!
